### ISSUE TITLE
Folder chmod

### ISSUE THREAD

**Issue by jssuttles** [isaacs/chmodr#9]
I'm trying to use this module to change the permissions of a folder and its contents including subfolders. Is there a way that I can do that?
As far as I can tell, looking at the code, this module only changes the permissions of the files inside the subfolders. I tried to fork it and fix it myself but I don't fully understand fs.chmod or your module.

Thanks.

**Comment by yoshuawuyts** [comment]
I think you're correct in your assesment; looked at the code and that seems to be the case indeed. Also checked the behavior on OS X and `chmod -R` seems to change the directory permissions too.

Not sure it should be changed tho, as this package is heavily relied on and may cause massive breakage.

**Comment by isaacs** [comment]
That's a bug. It should be fixed. We can bump the major version when publishing it to prevent breakage.

**Comment by mawni** [comment]
@jssuttles I just tested the `chmodr` to change the permissions of a directory and all its contents including files and subdirectories. It worked just fine. It changed the permissions of the given directory as well as all of its files and subdirectories. I tested it on Ubuntu 16.04 with node v7.3.0.

**Comment by jssuttles** [comment]
<img width="326" alt="screen shot 2017-01-02 at 8 49 29 am" src="https://cloud.githubusercontent.com/assets/8527741/21590401/7ec44cac-d0c9-11e6-8872-a78c0a6508c0.png">
<img width="324" alt="screen shot 2017-01-02 at 8 49 02 am" src="https://cloud.githubusercontent.com/assets/8527741/21590404/83b86be4-d0c9-11e6-948f-f43882c0d9f7.png">
<img width="506" alt="screen shot 2017-01-02 at 8 52 03 am" src="https://cloud.githubusercontent.com/assets/8527741/21590409/8e9ea744-d0c9-11e6-8de0-b6d0898ba390.png">
<img width="330" alt="screen shot 2017-01-02 at 8 52 16 am" src="https://cloud.githubusercontent.com/assets/8527741/21590411/907a241c-d0c9-11e6-9574-9b47067f8f07.png">
I think it's the dirmode function that's not working properly. It's setting everything to just --x--x--x instead of rwxrwxrwx for chmod -R 777

**Comment by jssuttles** [comment]
To fully copy 'chmod -R', wouldn't you have to set all folders to at least --x--x--x once and then backtrack up so that all folders match the permissions that you wanted them to be?

**Comment by jssuttles** [comment]
Nvm the previous posts, it appears that you do that. However, I guess I was expecting to be able to use a string '777'. It's my fault I guess. Tested with integer and it works. I'm closing this.

**Comment by jssuttles** [comment]
It shouldn't take a string '777' because fs.chmod doesn't either. So, nothing to worry about there either.
